apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport-ip 



spec:
  type: NodePort
  selector:
    app: my-web-app


  ports:
    - port: 8080 #services
      targetPort: 80 #pod
      nodePort: 30005