apiVersion: v1
kind: Pod
metadata: 
  name: my-web-app
spec:
  containers:
    - name: my-container
      image: emandesoky/pro_image
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80  